package com.example.util

import android.content.Context
import android.util.Log
import org.json.JSONObject
import java.io.File

object GoogleServicesConfigHelper {
    private var cachedClientId: String? = null

    /**
     * Extracts Web Client ID (client_type 3) dynamically from app/google-services.json
     * or generated resources without extra quotes or whitespace.
     */
    fun getWebClientId(context: Context): String {
        cachedClientId?.let { return it }

        val clean = { raw: String ->
            raw.trim()
                .removePrefix("\"").removeSuffix("\"")
                .removePrefix("'").removeSuffix("'")
                .trim()
        }

        // 1. Try reading from app/google-services.json on file system or asset
        val jsonString = try {
            val fileCandidates = listOf(
                File("app/google-services.json"),
                File("/app/google-services.json"),
                File("../app/google-services.json"),
                File("app/src/main/assets/google-services.json"),
                File(context.filesDir?.parentFile, "google-services.json"),
                File(context.filesDir, "google-services.json")
            )
            fileCandidates.firstOrNull { it.exists() }?.readText()
                ?: runCatching {
                    context.assets.open("google-services.json").bufferedReader().use { it.readText() }
                }.getOrNull()
        } catch (e: Exception) {
            null
        }

        if (!jsonString.isNullOrBlank()) {
            try {
                val root = JSONObject(jsonString)
                val clientArr = root.optJSONArray("client")
                if (clientArr != null) {
                    var candidateId: String? = null
                    for (i in 0 until clientArr.length()) {
                        val clientObj = clientArr.getJSONObject(i)
                        val clientInfo = clientObj.optJSONObject("client_info")
                        val androidClientInfo = clientInfo?.optJSONObject("android_client_info")
                        val pkgName = androidClientInfo?.optString("package_name")

                        val oauthArr = clientObj.optJSONArray("oauth_client") ?: continue
                        for (j in 0 until oauthArr.length()) {
                            val oauthObj = oauthArr.getJSONObject(j)
                            if (oauthObj.optInt("client_type") == 3) {
                                val clientId = clean(oauthObj.optString("client_id", ""))
                                if (clientId.isNotBlank()) {
                                    if (pkgName == context.packageName) {
                                        cachedClientId = clientId
                                        return clientId
                                    }
                                    if (candidateId == null) {
                                        candidateId = clientId
                                    }
                                }
                            }
                        }
                    }
                    if (!candidateId.isNullOrBlank()) {
                        cachedClientId = candidateId
                        return candidateId
                    }
                }
            } catch (e: Exception) {
                Log.w("GoogleServicesConfig", "Error parsing google-services.json: ${e.message}")
            }
        }

        // 2. Try R.string.default_web_client_id generated by Google Services plugin
        val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        if (resId != 0) {
            val resVal = runCatching { clean(context.getString(resId)) }.getOrNull()
            if (!resVal.isNullOrBlank()) {
                cachedClientId = resVal
                return resVal
            }
        }

        // 3. Fallback from google-services.json
        val defaultId = "668455931031-burt9863pi64rshdlmgenejnj27ep0d0.apps.googleusercontent.com"
        cachedClientId = defaultId
        return defaultId
    }
}
